# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrainSAR.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_test(object):
    def setupUi(self, test):
        test.setObjectName("test")
        test.resize(687, 494)
        self.centralwidget = QtWidgets.QWidget(test)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.modelname = QtWidgets.QLabel(self.centralwidget)
        self.modelname.setObjectName("modelname")
        self.gridLayout_2.addWidget(self.modelname, 2, 0, 1, 1)
        self.showCut = QtWidgets.QLabel(self.centralwidget)
        self.showCut.setObjectName("showCut")
        self.gridLayout_2.addWidget(self.showCut, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(50, 20, 50, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setObjectName("open")
        self.verticalLayout.addWidget(self.open)
        self.cut = QtWidgets.QPushButton(self.centralwidget)
        self.cut.setObjectName("cut")
        self.verticalLayout.addWidget(self.cut)
        self.LOAD = QtWidgets.QPushButton(self.centralwidget)
        self.LOAD.setObjectName("LOAD")
        self.verticalLayout.addWidget(self.LOAD)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.start.setFont(font)
        self.start.setObjectName("start")
        self.gridLayout_2.addWidget(self.start, 3, 0, 1, 1)
        self.log = QtWidgets.QLabel(self.centralwidget)
        self.log.setObjectName("log")
        self.gridLayout_2.addWidget(self.log, 0, 0, 1, 1)
        self.outputlabel = QtWidgets.QLabel(self.centralwidget)
        self.outputlabel.setObjectName("outputlabel")
        self.gridLayout_2.addWidget(self.outputlabel, 5, 0, 1, 1)
        self.showSAR = QtWidgets.QLabel(self.centralwidget)
        self.showSAR.setObjectName("showSAR")
        self.gridLayout_2.addWidget(self.showSAR, 0, 1, 6, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 8)
        self.gridLayout_2.setRowStretch(0, 3)
        self.gridLayout_2.setRowStretch(1, 3)
        self.gridLayout_2.setRowStretch(2, 1)
        self.gridLayout_2.setRowStretch(3, 1)
        self.gridLayout_2.setRowStretch(4, 3)
        self.gridLayout_2.setRowStretch(5, 1)
        test.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(test)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 687, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        test.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(test)
        self.statusbar.setObjectName("statusbar")
        test.setStatusBar(self.statusbar)
        self.openimage = QtWidgets.QAction(test)
        self.openimage.setObjectName("openimage")
        self.saveimage = QtWidgets.QAction(test)
        self.saveimage.setObjectName("saveimage")
        self.actionQuite_2 = QtWidgets.QAction(test)
        self.actionQuite_2.setObjectName("actionQuite_2")
        self.actionShow_input_SAR = QtWidgets.QAction(test)
        self.actionShow_input_SAR.setObjectName("actionShow_input_SAR")
        self.actionShow_output_SAR = QtWidgets.QAction(test)
        self.actionShow_output_SAR.setObjectName("actionShow_output_SAR")
        self.actionAbout_SAR_System = QtWidgets.QAction(test)
        self.actionAbout_SAR_System.setObjectName("actionAbout_SAR_System")
        self.menuFile.addAction(self.openimage)
        self.menuFile.addAction(self.saveimage)
        self.menuFile.addAction(self.actionQuite_2)
        self.menuView.addAction(self.actionShow_input_SAR)
        self.menuView.addAction(self.actionShow_output_SAR)
        self.menuHelp.addAction(self.actionAbout_SAR_System)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(test)
        self.open.clicked.connect(self.open.click)
        self.LOAD.clicked.connect(self.LOAD.click)
        self.start.clicked.connect(self.start.click)
        self.cut.clicked.connect(self.cut.click)
        QtCore.QMetaObject.connectSlotsByName(test)

    def retranslateUi(self, test):
        _translate = QtCore.QCoreApplication.translate
        test.setWindowTitle(_translate("test", "BrainSAR--System"))
        self.modelname.setText(_translate("test", "modelname"))
        self.showCut.setText(_translate("test", "showCUT"))
        self.open.setText(_translate("test", "打开SAR图片"))
        self.cut.setText(_translate("test", "裁剪SAR图片"))
        self.LOAD.setText(_translate("test", "Load ML model"))
        self.start.setText(_translate("test", "START"))
        self.log.setText(_translate("test", "showlog"))
        self.outputlabel.setText(_translate("test", "TextLabel"))
        self.showSAR.setText(_translate("test", "显示SAR图像"))
        self.menuFile.setTitle(_translate("test", "File"))
        self.menuView.setTitle(_translate("test", "View"))
        self.menuSettings.setTitle(_translate("test", "Settings"))
        self.menuHelp.setTitle(_translate("test", "Help"))
        self.openimage.setText(_translate("test", "Open Image"))
        self.saveimage.setText(_translate("test", "Save Image"))
        self.actionQuite_2.setText(_translate("test", "Quite"))
        self.actionShow_input_SAR.setText(_translate("test", "Show input SAR"))
        self.actionShow_output_SAR.setText(_translate("test", "Show output SAR"))
        self.actionAbout_SAR_System.setText(_translate("test", "About  SAR System"))
